"""create student

Revision ID: 13c4d2f90991
Revises: ff5ed09c1d82
Create Date: 2023-09-20 17:05:47.569340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c4d2f90991'
down_revision: Union[str, None] = 'ff5ed09c1d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('educational_platform_id', sa.UUID(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['educational_platform_id'], ['educational_platforms.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
