"""add all

Revision ID: 2ad6160bcdcc
Revises: 99b2e645adbc
Create Date: 2023-09-20 17:47:45.309163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad6160bcdcc'
down_revision: Union[str, None] = '99b2e645adbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chances',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chance_modifier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('spin_statistics',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('spin_count', sa.Integer(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'host_id')
    )
    op.add_column('teachers', sa.Column('taught_subject_ids', postgresql.ARRAY(sa.UUID()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'taught_subject_ids')
    op.drop_table('spin_statistics')
    op.drop_table('chances')
    # ### end Alembic commands ###
